//
//  HistoricalAdministrations.swift
//  Global Thermal Nuclear War
//
//  Historical US Presidents and Cabinet Members from Nuclear Age (1945-2025)
//  Data compiled from historical records and government sources
//

import Foundation
import SwiftUI

/// Historical administration period
struct Administration: Identifiable, Codable {
    let id: String
    let name: String
    let president: String
    let years: String
    let startYear: Int
    let endYear: Int
    let party: String
    let advisors: [Advisor]

    var description: String {
        "\(president) (\(years)) - \(party)"
    }
}

extension Advisor {
    /// Get all historical administrations from 1789 to present (46 total)
    static func allAdministrations() -> [Administration] {
        // For now, return nuclear age only (pre-nuclear coming soon)
        // TODO: Add preNuclearAdministrations() once file compiles
        return [
            trumanAdministration(),
            eisenhowerAdministration(),
            kennedyAdministration(),
            johnsonAdministration(),
            nixonAdministration(),
            fordAdministration(),
            carterAdministration(),
            reaganAdministration(),
            bushSrAdministration(),
            clintonAdministration(),
            bushJrAdministration(),
            obamaAdministration(),
            trumpFirstAdministration(),
            bidenAdministration(),
            trumpSecondAdministration()
        ]
    }

    // MARK: - Truman Administration (1945-1953)

    static func trumanAdministration() -> Administration {
        Administration(
            id: "truman",
            name: "Truman Administration",
            president: "Harry S. Truman",
            years: "1945-1953",
            startYear: 1945,
            endYear: 1953,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "truman",
                    name: "Harry S. Truman",
                    title: "President",
                    department: "Executive Office",
                    bio: "33rd President, Made decision to use atomic bombs on Japan",
                    expertise: 70,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 50,
                    hawkishness: 75,
                    interventionism: 70,
                    fiscalConservatism: 60,
                    adviceAreas: [.militaryStrike, .nuclearWeapons, .diplomacy],
                    currentAdvice: "The buck stops here. We must make the hard decisions.",
                    adviceType: .military,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "acheson",
                    name: "Dean Acheson",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Architect of Cold War containment policy",
                    expertise: 90,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 55,
                    hawkishness: 70,
                    interventionism: 75,
                    fiscalConservatism: 65,
                    adviceAreas: [.diplomacy, .economicSanctions],
                    currentAdvice: "We must contain Soviet expansion through strength and alliances.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "marshall",
                    name: "George C. Marshall",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Five-star General, Marshall Plan architect",
                    expertise: 100,
                    loyalty: 90,
                    influence: 95,
                    publicSupport: 85,
                    hawkishness: 60,
                    interventionism: 70,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .diplomacy],
                    currentAdvice: "Military strength must be balanced with diplomatic wisdom.",
                    adviceType: .military,
                    portraitColor: "#556B2F"
                ),
                Advisor(
                    id: "barkley",
                    name: "Alben W. Barkley",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "35th VP, 'The Veep', Senate Majority Leader, elder statesman",
                    expertise: 75,
                    loyalty: 95,
                    influence: 70,
                    publicSupport: 65,
                    hawkishness: 50,
                    interventionism: 55,
                    fiscalConservatism: 45,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "The Senate will support you, Mr. President. You have the votes.",
                    adviceType: .domestic,
                    portraitColor: "#6A5ACD"
                ),
                Advisor(
                    id: "smith_cia",
                    name: "Gen. Walter Bedell Smith",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "'Beetle' Smith, Eisenhower's WWII chief of staff, Professional intelligence officer",
                    expertise: 90,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 70,
                    interventionism: 75,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Our HUMINT on Soviet intentions is fragmentary, sir. We must assume the worst.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "snyder",
                    name: "John W. Snyder",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "St. Louis banker, Truman's closest friend, Marshall Plan financing",
                    expertise: 75,
                    loyalty: 95,
                    influence: 70,
                    publicSupport: 45,
                    hawkishness: 30,
                    interventionism: 40,
                    fiscalConservatism: 80,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Rebuilding Europe costs money, Harry, but it's the right investment.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                ),
                Advisor(
                    id: "clark_ag",
                    name: "Tom C. Clark",
                    title: "Attorney General",
                    department: "Justice",
                    bio: "Led internal security programs, Later Supreme Court Justice",
                    expertise: 80,
                    loyalty: 85,
                    influence: 75,
                    publicSupport: 55,
                    hawkishness: 60,
                    interventionism: 55,
                    fiscalConservatism: 60,
                    adviceAreas: [.intelligence, .legal],
                    currentAdvice: "Soviet infiltration is a real threat. We must be vigilant on the home front.",
                    adviceType: .intelligence,
                    portraitColor: "#8B0000"
                )
            ]
        )
    }

    // MARK: - Eisenhower Administration (1953-1961)

    static func eisenhowerAdministration() -> Administration {
        Administration(
            id: "eisenhower",
            name: "Eisenhower Administration",
            president: "Dwight D. Eisenhower",
            years: "1953-1961",
            startYear: 1953,
            endYear: 1961,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "eisenhower",
                    name: "Dwight D. Eisenhower",
                    title: "President",
                    department: "Executive Office",
                    bio: "34th President, Supreme Allied Commander WWII, Warned of military-industrial complex",
                    expertise: 95,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 70,
                    hawkishness: 60,
                    interventionism: 65,
                    fiscalConservatism: 75,
                    adviceAreas: [.militaryStrike, .nuclearWeapons, .diplomacy],
                    currentAdvice: "Peace through strength. But we must beware the military-industrial complex.",
                    adviceType: .military,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "dulles_state",
                    name: "John Foster Dulles",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Cold warrior, Massive retaliation doctrine",
                    expertise: 85,
                    loyalty: 90,
                    influence: 90,
                    publicSupport: 60,
                    hawkishness: 85,
                    interventionism: 80,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .nuclearWeapons],
                    currentAdvice: "We must respond with massive retaliation to any Soviet aggression.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "dulles_cia",
                    name: "Allen Dulles",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Spymaster, Covert operations expert, Bay of Pigs architect",
                    expertise: 95,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 80,
                    interventionism: 90,
                    fiscalConservatism: 65,
                    adviceAreas: [.covertOps, .intelligence],
                    currentAdvice: "We have assets in place for covert action, Mr. President.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "nixon_vp",
                    name: "Richard Nixon",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "California Senator, Checker's speech, Debated Khrushchev in Moscow kitchen",
                    expertise: 75,
                    loyalty: 80,
                    influence: 80,
                    publicSupport: 55,
                    hawkishness: 75,
                    interventionism: 70,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .covertOps],
                    currentAdvice: "The Soviets respect toughness. We must not show weakness anywhere.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "wilson_secdef",
                    name: "Charles 'Engine Charlie' Wilson",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Former GM CEO, 'What's good for General Motors is good for America'",
                    expertise: 70,
                    loyalty: 85,
                    influence: 75,
                    publicSupport: 55,
                    hawkishness: 65,
                    interventionism: 60,
                    fiscalConservatism: 80,
                    adviceAreas: [.militaryStrike, .domesticPolicy],
                    currentAdvice: "A strong economy is the backbone of our national defense, sir.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "cutler_nsa",
                    name: "Robert Cutler",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "First formal National Security Advisor, Boston banker, NSC architect",
                    expertise: 80,
                    loyalty: 90,
                    influence: 80,
                    publicSupport: 45,
                    hawkishness: 65,
                    interventionism: 65,
                    fiscalConservatism: 75,
                    adviceAreas: [.intelligence, .militaryStrike, .diplomacy],
                    currentAdvice: "The NSC has reviewed all options, Mr. President. Massive retaliation remains credible.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "humphrey_treasury",
                    name: "George M. Humphrey",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Ohio industrialist, Balanced budgets hawk, 'A chance for a depression'",
                    expertise: 80,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 60,
                    hawkishness: 30,
                    interventionism: 35,
                    fiscalConservatism: 95,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "We cannot afford to fight two wars simultaneously — we must be selective.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Kennedy Administration (1961-1963)

    static func kennedyAdministration() -> Administration {
        Administration(
            id: "kennedy",
            name: "Kennedy Administration",
            president: "John F. Kennedy",
            years: "1961-1963",
            startYear: 1961,
            endYear: 1963,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "kennedy",
                    name: "John F. Kennedy",
                    title: "President",
                    department: "Executive Office",
                    bio: "35th President, Cuban Missile Crisis, Youngest elected president",
                    expertise: 75,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 70,
                    hawkishness: 50,
                    interventionism: 60,
                    fiscalConservatism: 55,
                    adviceAreas: [.diplomacy, .militaryStrike, .nuclearWeapons],
                    currentAdvice: "We cannot let fear drive our decisions, but we must be prepared.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "mcnamara",
                    name: "Robert McNamara",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Systems analyst, Vietnam War architect, Later regretted escalation",
                    expertise: 90,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 60,
                    hawkishness: 70,
                    interventionism: 75,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "The numbers suggest a surgical strike could succeed, but the risks are enormous.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "rusk",
                    name: "Dean Rusk",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Cuban Missile Crisis negotiator",
                    expertise: 85,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 65,
                    hawkishness: 55,
                    interventionism: 65,
                    fiscalConservatism: 65,
                    adviceAreas: [.diplomacy],
                    currentAdvice: "We must pursue backchannel negotiations while maintaining our quarantine.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "rfk",
                    name: "Robert F. Kennedy",
                    title: "Attorney General",
                    department: "Justice",
                    bio: "President's brother, Key advisor during Cuban Missile Crisis, ExComm moderating voice",
                    expertise: 75,
                    loyalty: 100,
                    influence: 90,
                    publicSupport: 70,
                    hawkishness: 40,
                    interventionism: 50,
                    fiscalConservatism: 55,
                    adviceAreas: [.diplomacy, .legal],
                    currentAdvice: "We must find a peaceful solution. A nuclear exchange would be catastrophic.",
                    adviceType: .diplomatic,
                    portraitColor: "#800080"
                ),
                Advisor(
                    id: "lbj_vp",
                    name: "Lyndon B. Johnson",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Senate Majority Leader, Southern Democrat, Sidelined VP",
                    expertise: 85,
                    loyalty: 70,
                    influence: 75,
                    publicSupport: 55,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 45,
                    adviceAreas: [.domesticPolicy, .militaryStrike],
                    currentAdvice: "We should hit them hard before they move those missiles. No half-measures.",
                    adviceType: .military,
                    portraitColor: "#CD853F"
                ),
                Advisor(
                    id: "mccone",
                    name: "John McCone",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "AEC Chairman, Predicted Soviet missiles in Cuba, Hawkish DCI",
                    expertise: 88,
                    loyalty: 80,
                    influence: 85,
                    publicSupport: 55,
                    hawkishness: 80,
                    interventionism: 85,
                    fiscalConservatism: 70,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "The Soviets have nuclear warheads already on Cuban soil, Mr. President. I staked my career on this.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "bundy",
                    name: "McGeorge Bundy",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Harvard Dean, ExComm key player, Intellectual hawk",
                    expertise: 92,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 55,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .militaryStrike, .diplomacy],
                    currentAdvice: "The quarantine is the right move — shows resolve without the finality of an airstrike.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "dillon",
                    name: "Douglas Dillon",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Republican investment banker, Kennedy's bipartisan pick, Fiscal conservative",
                    expertise: 82,
                    loyalty: 75,
                    influence: 75,
                    publicSupport: 55,
                    hawkishness: 40,
                    interventionism: 45,
                    fiscalConservatism: 85,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Economic pressure on Cuba will complement the blockade. Isolate them financially.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Johnson Administration (1963-1969)

    static func johnsonAdministration() -> Administration {
        Administration(
            id: "johnson",
            name: "Johnson Administration",
            president: "Lyndon B. Johnson",
            years: "1963-1969",
            startYear: 1963,
            endYear: 1969,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "johnson",
                    name: "Lyndon B. Johnson",
                    title: "President",
                    department: "Executive Office",
                    bio: "36th President, Vietnam War escalation, Great Society programs",
                    expertise: 80,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 50,
                    hawkishness: 70,
                    interventionism: 80,
                    fiscalConservatism: 40,
                    adviceAreas: [.militaryStrike, .domesticPolicy],
                    currentAdvice: "We will not lose to communism. Do what's necessary.",
                    adviceType: .military,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "mcnamara_lbj",
                    name: "Robert McNamara",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Continued from Kennedy, Vietnam War expansion, Later deeply regretted war",
                    expertise: 90,
                    loyalty: 80,
                    influence: 85,
                    publicSupport: 45,
                    hawkishness: 75,
                    interventionism: 80,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Escalation may be necessary to achieve our objectives in Vietnam.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "rusk_lbj",
                    name: "Dean Rusk",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Carried over from Kennedy, steadfast Vietnam supporter",
                    expertise: 85,
                    loyalty: 90,
                    influence: 80,
                    publicSupport: 40,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 60,
                    adviceAreas: [.diplomacy, .militaryStrike],
                    currentAdvice: "We cannot abandon South Vietnam. The credibility of our commitments is at stake.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "humphrey_vp",
                    name: "Hubert H. Humphrey",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "'Happy Warrior', Civil rights champion, Tortured by Vietnam War",
                    expertise: 80,
                    loyalty: 85,
                    influence: 75,
                    publicSupport: 60,
                    hawkishness: 45,
                    interventionism: 55,
                    fiscalConservatism: 40,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "Mr. President, we need a negotiated settlement. This war is tearing the country apart.",
                    adviceType: .diplomatic,
                    portraitColor: "#6A5ACD"
                ),
                Advisor(
                    id: "helms",
                    name: "Richard Helms",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Career CIA officer, Vietnam intelligence, 'The man who kept the secrets'",
                    expertise: 92,
                    loyalty: 75,
                    influence: 85,
                    publicSupport: 45,
                    hawkishness: 65,
                    interventionism: 75,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Our HUMINT from Hanoi is uncertain. Enemy strength is higher than reported.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "rostow",
                    name: "Walt Rostow",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "'The Hawk of Hawks', Bombing campaign architect, Unrepentant Vietnam advocate",
                    expertise: 85,
                    loyalty: 95,
                    influence: 85,
                    publicSupport: 35,
                    hawkishness: 95,
                    interventionism: 95,
                    fiscalConservatism: 55,
                    adviceAreas: [.militaryStrike, .intelligence],
                    currentAdvice: "Bomb them into the Stone Age if we must. Victory requires resolve.",
                    adviceType: .military,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "fowler",
                    name: "Henry H. Fowler",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Virginia lawyer, War financing, Dollar stability under Great Society strain",
                    expertise: 75,
                    loyalty: 85,
                    influence: 70,
                    publicSupport: 45,
                    hawkishness: 35,
                    interventionism: 45,
                    fiscalConservatism: 60,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "We can fund guns and butter for now, sir — but not indefinitely.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Nixon Administration (1969-1974)

    static func nixonAdministration() -> Administration {
        Administration(
            id: "nixon",
            name: "Nixon Administration",
            president: "Richard Nixon",
            years: "1969-1974",
            startYear: 1969,
            endYear: 1974,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "nixon",
                    name: "Richard Nixon",
                    title: "President",
                    department: "Executive Office",
                    bio: "37th President, Détente with USSR, Opening to China, Watergate",
                    expertise: 85,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 40,
                    hawkishness: 70,
                    interventionism: 75,
                    fiscalConservatism: 65,
                    adviceAreas: [.diplomacy, .covertOps, .nuclearWeapons],
                    currentAdvice: "I am not a crook. But I will do what it takes to win.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "kissinger",
                    name: "Henry Kissinger",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Architect of détente, Realpolitik master, Nobel Peace Prize",
                    expertise: 100,
                    loyalty: 80,
                    influence: 95,
                    publicSupport: 60,
                    hawkishness: 60,
                    interventionism: 85,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .covertOps, .militaryStrike],
                    currentAdvice: "Power is the ultimate aphrodisiac. We must use it strategically.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "agnew",
                    name: "Spiro Agnew",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Maryland Governor, 'Nattering nabobs of negativism', Resigned for tax evasion",
                    expertise: 55,
                    loyalty: 80,
                    influence: 65,
                    publicSupport: 45,
                    hawkishness: 75,
                    interventionism: 65,
                    fiscalConservatism: 75,
                    adviceAreas: [.domesticPolicy],
                    currentAdvice: "The liberal media and their nattering nabobs won't stop us.",
                    adviceType: .domestic,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "laird",
                    name: "Melvin Laird",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "'Vietnamization' architect, Wisconsin Congressman, Political pragmatist",
                    expertise: 85,
                    loyalty: 80,
                    influence: 85,
                    publicSupport: 55,
                    hawkishness: 65,
                    interventionism: 65,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Vietnamization is working — train the South Vietnamese to fight their own war.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "helms_nixon",
                    name: "Richard Helms",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Carried over from LBJ, Watergate entanglements, Chile coup",
                    expertise: 92,
                    loyalty: 65,
                    influence: 80,
                    publicSupport: 40,
                    hawkishness: 70,
                    interventionism: 80,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Our assets in Chile are ready, sir. Allende can be... managed.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "connally",
                    name: "John Connally",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Texas Democrat turned Republican, 'Nixon Shock', Ended gold standard",
                    expertise: 82,
                    loyalty: 80,
                    influence: 85,
                    publicSupport: 55,
                    hawkishness: 55,
                    interventionism: 50,
                    fiscalConservatism: 65,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "The dollar is our currency, but it's their problem. Let them adjust.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Ford Administration (1974-1977)

    static func fordAdministration() -> Administration {
        Administration(
            id: "ford",
            name: "Ford Administration",
            president: "Gerald Ford",
            years: "1974-1977",
            startYear: 1974,
            endYear: 1977,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "ford",
                    name: "Gerald Ford",
                    title: "President",
                    department: "Executive Office",
                    bio: "38th President, Only unelected president, Pardoned Nixon",
                    expertise: 70,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 45,
                    hawkishness: 55,
                    interventionism: 60,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "Our long national nightmare is over. Let's heal and move forward.",
                    adviceType: .domestic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "kissinger_ford",
                    name: "Henry Kissinger",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Continued from Nixon, Remained dominant foreign policy voice",
                    expertise: 100,
                    loyalty: 75,
                    influence: 90,
                    publicSupport: 55,
                    hawkishness: 60,
                    interventionism: 85,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .covertOps],
                    currentAdvice: "Détente remains our best path forward, Mr. President.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "rockefeller_vp",
                    name: "Nelson Rockefeller",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "NY Governor, Liberal Republican, Also unelected VP, Attica and drug law legacy",
                    expertise: 85,
                    loyalty: 70,
                    influence: 80,
                    publicSupport: 60,
                    hawkishness: 55,
                    interventionism: 65,
                    fiscalConservatism: 55,
                    adviceAreas: [.domesticPolicy, .diplomacy],
                    currentAdvice: "America must remain engaged in the world. Isolationism is not the answer.",
                    adviceType: .diplomatic,
                    portraitColor: "#6A5ACD"
                ),
                Advisor(
                    id: "rumsfeld_ford",
                    name: "Donald Rumsfeld",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Chief of Staff then SecDef, Opposed Kissinger détente, Team B hawk",
                    expertise: 85,
                    loyalty: 80,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 85,
                    interventionism: 75,
                    fiscalConservatism: 75,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "The Soviets are cheating on détente. We're falling behind militarily.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "bush_cia",
                    name: "George H.W. Bush",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "UN Ambassador, RNC Chair, Began intelligence career, Rebuilt CIA post-Church Committee",
                    expertise: 80,
                    loyalty: 85,
                    influence: 80,
                    publicSupport: 60,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 70,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "The Church Committee damaged our intelligence capabilities. We need to rebuild.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "scowcroft_ford",
                    name: "Brent Scowcroft",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Air Force General, 'The model National Security Advisor', Pragmatic realist",
                    expertise: 93,
                    loyalty: 90,
                    influence: 88,
                    publicSupport: 55,
                    hawkishness: 60,
                    interventionism: 65,
                    fiscalConservatism: 70,
                    adviceAreas: [.intelligence, .diplomacy, .militaryStrike],
                    currentAdvice: "Our alliances are our greatest strategic asset. We must not squander them.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "simon",
                    name: "William Simon",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Wall Street bond trader, Opposed NYC bailout, 'Drop dead' philosophy",
                    expertise: 80,
                    loyalty: 80,
                    influence: 75,
                    publicSupport: 45,
                    hawkishness: 35,
                    interventionism: 30,
                    fiscalConservatism: 95,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "No bailouts. Free markets require discipline — even when it's painful.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Carter Administration (1977-1981)

    static func carterAdministration() -> Administration {
        Administration(
            id: "carter",
            name: "Carter Administration",
            president: "Jimmy Carter",
            years: "1977-1981",
            startYear: 1977,
            endYear: 1981,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "carter",
                    name: "Jimmy Carter",
                    title: "President",
                    department: "Executive Office",
                    bio: "39th President, Human rights advocate, Iran hostage crisis, Camp David Accords",
                    expertise: 70,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 45,
                    hawkishness: 30,
                    interventionism: 40,
                    fiscalConservatism: 55,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "We must pursue peace with the same vigor we prepare for war.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "vance",
                    name: "Cyrus Vance",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Diplomat, Resigned over Iran rescue attempt",
                    expertise: 85,
                    loyalty: 75,
                    influence: 80,
                    publicSupport: 50,
                    hawkishness: 25,
                    interventionism: 35,
                    fiscalConservatism: 60,
                    adviceAreas: [.diplomacy],
                    currentAdvice: "Diplomacy and negotiation must always come first, Mr. President.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "brzezinski",
                    name: "Zbigniew Brzezinski",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Hardline anti-Soviet strategist, Afghanistan policy architect",
                    expertise: 95,
                    loyalty: 90,
                    influence: 95,
                    publicSupport: 55,
                    hawkishness: 75,
                    interventionism: 80,
                    fiscalConservatism: 65,
                    adviceAreas: [.militaryStrike, .intelligence, .covertOps],
                    currentAdvice: "The Soviets only understand strength. We must be prepared to use force.",
                    adviceType: .military,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "mondale",
                    name: "Walter Mondale",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Minnesota Senator, First 'governing VP', Later lost landslide to Reagan",
                    expertise: 80,
                    loyalty: 90,
                    influence: 75,
                    publicSupport: 55,
                    hawkishness: 30,
                    interventionism: 40,
                    fiscalConservatism: 40,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "Human rights must be at the center of our foreign policy.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "brown_secdef",
                    name: "Harold Brown",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Nuclear physicist, Caltech president, Modernized nuclear arsenal, PD-59",
                    expertise: 95,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 55,
                    hawkishness: 65,
                    interventionism: 60,
                    fiscalConservatism: 65,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "We must update our targeting doctrine to include Soviet military assets, not just cities.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "turner_cia",
                    name: "Adm. Stansfield Turner",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Naval Academy classmate of Carter, Gutted HUMINT, Relied on technical intel",
                    expertise: 75,
                    loyalty: 90,
                    influence: 70,
                    publicSupport: 45,
                    hawkishness: 55,
                    interventionism: 50,
                    fiscalConservatism: 60,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Our satellite reconnaissance shows Soviet forces mobilizing near Afghanistan.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "blumenthal",
                    name: "W. Michael Blumenthal",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "German-born refugee, CEO, Dollar devaluation, Resigned under pressure",
                    expertise: 78,
                    loyalty: 75,
                    influence: 70,
                    publicSupport: 40,
                    hawkishness: 30,
                    interventionism: 40,
                    fiscalConservatism: 65,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Oil shocks are strangling the economy. Energy independence must be our priority.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Reagan Administration (1981-1989)

    static func reaganAdministration() -> Administration {
        Administration(
            id: "reagan",
            name: "Reagan Administration",
            president: "Ronald Reagan",
            years: "1981-1989",
            startYear: 1981,
            endYear: 1989,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "reagan",
                    name: "Ronald Reagan",
                    title: "President",
                    department: "Executive Office",
                    bio: "40th President, 'Mr. Gorbachev, tear down this wall!', SDI Star Wars, Ended Cold War",
                    expertise: 70,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 65,
                    hawkishness: 80,
                    interventionism: 75,
                    fiscalConservatism: 80,
                    adviceAreas: [.militaryStrike, .nuclearWeapons, .economicSanctions],
                    currentAdvice: "We win, they lose. Peace through strength.",
                    adviceType: .military,
                    portraitColor: "#FFD700"
                ),
                Advisor(
                    id: "shultz",
                    name: "George Shultz",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Negotiated with Gorbachev, Arms control advocate",
                    expertise: 90,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 70,
                    hawkishness: 50,
                    interventionism: 65,
                    fiscalConservatism: 75,
                    adviceAreas: [.diplomacy, .economicSanctions],
                    currentAdvice: "Mr. President, we're making progress with Gorbachev. Let's keep negotiating.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "weinberger",
                    name: "Caspar Weinberger",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Military buildup architect, 'Cap the Knife'",
                    expertise: 85,
                    loyalty: 95,
                    influence: 90,
                    publicSupport: 60,
                    hawkishness: 85,
                    interventionism: 70,
                    fiscalConservatism: 80,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Our military buildup is working, sir. The Soviets can't keep up.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "casey",
                    name: "William Casey",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Covert operations mastermind, Iran-Contra architect, Died before testimony",
                    expertise: 90,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 85,
                    interventionism: 95,
                    fiscalConservatism: 75,
                    adviceAreas: [.covertOps, .intelligence],
                    currentAdvice: "We have assets worldwide ready for covert action, Mr. President.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "bush_vp",
                    name: "George H.W. Bush",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Former CIA Director, UN Ambassador, China envoy — the most experienced VP ever",
                    expertise: 90,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 60,
                    hawkishness: 60,
                    interventionism: 70,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .intelligence, .militaryStrike],
                    currentAdvice: "We have the intelligence community's full support, Mr. President.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "powell_nsa",
                    name: "Gen. Colin Powell",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "First Black NSA, Army General, Later Chairman of Joint Chiefs",
                    expertise: 93,
                    loyalty: 88,
                    influence: 90,
                    publicSupport: 75,
                    hawkishness: 65,
                    interventionism: 65,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .intelligence, .diplomacy],
                    currentAdvice: "Any use of force should have clear objectives, overwhelming resources, and an exit strategy.",
                    adviceType: .military,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "kirkpatrick",
                    name: "Jeane Kirkpatrick",
                    title: "UN Ambassador",
                    department: "State",
                    bio: "Democrat turned Reagan Republican, Distinguished between authoritarian and totalitarian regimes",
                    expertise: 88,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 60,
                    hawkishness: 80,
                    interventionism: 75,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .militaryStrike],
                    currentAdvice: "We should distinguish between friends who are imperfect and enemies who are hostile.",
                    adviceType: .diplomatic,
                    portraitColor: "#FF8C00"
                ),
                Advisor(
                    id: "baker_reagan",
                    name: "James Baker III",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Texas lawyer, White House Chief of Staff, Plaza Accord architect",
                    expertise: 90,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 65,
                    hawkishness: 40,
                    interventionism: 50,
                    fiscalConservatism: 75,
                    adviceAreas: [.economicSanctions, .diplomacy],
                    currentAdvice: "The Plaza Accord will rebalance our trade position. Economic leverage is powerful.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Bush Sr. Administration (1989-1993)

    static func bushSrAdministration() -> Administration {
        Administration(
            id: "bush_sr",
            name: "Bush Sr. Administration",
            president: "George H.W. Bush",
            years: "1989-1993",
            startYear: 1989,
            endYear: 1993,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "bush_sr",
                    name: "George H.W. Bush",
                    title: "President",
                    department: "Executive Office",
                    bio: "41st President, Former CIA Director, Gulf War, End of Cold War",
                    expertise: 90,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 60,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 75,
                    adviceAreas: [.diplomacy, .militaryStrike, .intelligence],
                    currentAdvice: "We must build a new world order based on cooperation.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "baker",
                    name: "James Baker",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Master negotiator, Managed German reunification",
                    expertise: 95,
                    loyalty: 90,
                    influence: 95,
                    publicSupport: 70,
                    hawkishness: 50,
                    interventionism: 65,
                    fiscalConservatism: 80,
                    adviceAreas: [.diplomacy, .economicSanctions],
                    currentAdvice: "We can negotiate from a position of strength, Mr. President.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "cheney",
                    name: "Dick Cheney",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Gulf War architect, Later VP under Bush Jr.",
                    expertise: 90,
                    loyalty: 90,
                    influence: 90,
                    publicSupport: 60,
                    hawkishness: 90,
                    interventionism: 85,
                    fiscalConservatism: 75,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Sir, we have overwhelming military superiority. We should use it.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "powell",
                    name: "General Colin Powell",
                    title: "Chairman, Joint Chiefs",
                    department: "Defense",
                    bio: "Four-star General, Gulf War commander, Powell Doctrine",
                    expertise: 95,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 80,
                    hawkishness: 55,
                    interventionism: 50,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike],
                    currentAdvice: "Use overwhelming force if we go in, but exhaust diplomacy first.",
                    adviceType: .military,
                    portraitColor: "#556B2F"
                ),
                Advisor(
                    id: "quayle",
                    name: "Dan Quayle",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Indiana Senator, Gaffe-prone but supportive VP, 'Potatoe' incident",
                    expertise: 60,
                    loyalty: 95,
                    influence: 60,
                    publicSupport: 35,
                    hawkishness: 70,
                    interventionism: 65,
                    fiscalConservatism: 75,
                    adviceAreas: [.domesticPolicy],
                    currentAdvice: "What a waste it is to lose one's mind — not having a mind is very wasteful.",
                    adviceType: .domestic,
                    portraitColor: "#CD853F"
                ),
                Advisor(
                    id: "webster_cia",
                    name: "William Webster",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "FBI Director turned DCI, Former federal judge, Cleaned up post-Casey CIA",
                    expertise: 80,
                    loyalty: 85,
                    influence: 78,
                    publicSupport: 60,
                    hawkishness: 55,
                    interventionism: 60,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Our intelligence confirms Iraqi forces in Kuwait are substantial. This won't be easy.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "scowcroft_bushsr",
                    name: "Brent Scowcroft",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "'Prudent realist', Managed Cold War end and Gulf War, Opposed Iraq War II",
                    expertise: 95,
                    loyalty: 92,
                    influence: 93,
                    publicSupport: 65,
                    hawkishness: 58,
                    interventionism: 62,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .intelligence, .militaryStrike],
                    currentAdvice: "We've achieved our objectives in Kuwait. Advancing to Baghdad would destabilize the region.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "brady",
                    name: "Nicholas Brady",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "New Jersey Senator, Brady Plan for Third World debt relief",
                    expertise: 80,
                    loyalty: 85,
                    influence: 78,
                    publicSupport: 55,
                    hawkishness: 35,
                    interventionism: 40,
                    fiscalConservatism: 80,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Sanctions against Iraq must be maintained. Economic pressure is working.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Clinton Administration (1993-2001)

    static func clintonAdministration() -> Administration {
        Administration(
            id: "clinton",
            name: "Clinton Administration",
            president: "Bill Clinton",
            years: "1993-2001",
            startYear: 1993,
            endYear: 2001,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "clinton",
                    name: "Bill Clinton",
                    title: "President",
                    department: "Executive Office",
                    bio: "42nd President, Balanced budgets, Kosovo intervention, Lewinsky scandal",
                    expertise: 75,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 60,
                    hawkishness: 45,
                    interventionism: 60,
                    fiscalConservatism: 55,
                    adviceAreas: [.diplomacy, .economicSanctions, .domesticPolicy],
                    currentAdvice: "We need to focus on the economy. It's the economy, stupid.",
                    adviceType: .economic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "albright",
                    name: "Madeleine Albright",
                    title: "Secretary of State",
                    department: "State",
                    bio: "First female Secretary of State, Czech-born refugee, Kosovo intervention advocate",
                    expertise: 85,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 65,
                    hawkishness: 65,
                    interventionism: 75,
                    fiscalConservatism: 55,
                    adviceAreas: [.diplomacy, .militaryStrike],
                    currentAdvice: "What's the point of having this superb military if we can't use it?",
                    adviceType: .diplomatic,
                    portraitColor: "#FF1493"
                ),
                Advisor(
                    id: "gore",
                    name: "Al Gore",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Tennessee Senator, Reinventing Government, 'No controlling legal authority'",
                    expertise: 80,
                    loyalty: 85,
                    influence: 78,
                    publicSupport: 55,
                    hawkishness: 50,
                    interventionism: 60,
                    fiscalConservatism: 50,
                    adviceAreas: [.domesticPolicy, .diplomacy],
                    currentAdvice: "We need a foreign policy that supports democracy and human rights globally.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "cohen",
                    name: "William Cohen",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Maine Republican Senator, Clinton's bipartisan SecDef, Kosovo War",
                    expertise: 82,
                    loyalty: 75,
                    influence: 80,
                    publicSupport: 65,
                    hawkishness: 60,
                    interventionism: 65,
                    fiscalConservatism: 65,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Air power can achieve our objectives in Kosovo without ground troops.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "tenet_clinton",
                    name: "George Tenet",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "NSC staffer turned DCI, Bridged Clinton-Bush era, 'Slam dunk' on WMDs",
                    expertise: 80,
                    loyalty: 78,
                    influence: 82,
                    publicSupport: 50,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 60,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Bin Laden determined to strike in US. Al-Qaeda is our most pressing threat.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "berger",
                    name: "Sandy Berger",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Trade lawyer, Kosovo crisis manager, Later classified documents scandal",
                    expertise: 82,
                    loyalty: 88,
                    influence: 83,
                    publicSupport: 50,
                    hawkishness: 55,
                    interventionism: 65,
                    fiscalConservatism: 55,
                    adviceAreas: [.intelligence, .diplomacy, .militaryStrike],
                    currentAdvice: "Kosovo requires military intervention. Ethnic cleansing cannot stand.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "rubin",
                    name: "Robert Rubin",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Goldman Sachs co-chairman, Budget surplus architect, Strong dollar policy",
                    expertise: 95,
                    loyalty: 85,
                    influence: 92,
                    publicSupport: 70,
                    hawkishness: 30,
                    interventionism: 40,
                    fiscalConservatism: 70,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Budget discipline is driving the economic boom. Don't squander the surplus.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Bush Jr. Administration (2001-2009)

    static func bushJrAdministration() -> Administration {
        Administration(
            id: "bush_jr",
            name: "Bush Jr. Administration",
            president: "George W. Bush",
            years: "2001-2009",
            startYear: 2001,
            endYear: 2009,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "bush_jr",
                    name: "George W. Bush",
                    title: "President",
                    department: "Executive Office",
                    bio: "43rd President, 9/11, Iraq War, War on Terror",
                    expertise: 60,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 50,
                    hawkishness: 85,
                    interventionism: 90,
                    fiscalConservatism: 60,
                    adviceAreas: [.militaryStrike, .covertOps],
                    currentAdvice: "You're either with us or against us.",
                    adviceType: .military,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "cheney_vp",
                    name: "Dick Cheney",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Most powerful VP in history, Iraq War architect",
                    expertise: 90,
                    loyalty: 95,
                    influence: 95,
                    publicSupport: 35,
                    hawkishness: 95,
                    interventionism: 95,
                    fiscalConservatism: 75,
                    adviceAreas: [.militaryStrike, .nuclearWeapons, .covertOps],
                    currentAdvice: "We have to work the dark side. The gloves come off.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "powell_state",
                    name: "Colin Powell",
                    title: "Secretary of State",
                    department: "State",
                    bio: "First Black Secretary of State, Resigned over Iraq War",
                    expertise: 90,
                    loyalty: 70,
                    influence: 80,
                    publicSupport: 75,
                    hawkishness: 55,
                    interventionism: 55,
                    fiscalConservatism: 70,
                    adviceAreas: [.diplomacy, .militaryStrike],
                    currentAdvice: "Mr. President, we need more evidence before military action.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "rumsfeld",
                    name: "Donald Rumsfeld",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Iraq War architect, 'Known unknowns' quote",
                    expertise: 85,
                    loyalty: 85,
                    influence: 90,
                    publicSupport: 40,
                    hawkishness: 90,
                    interventionism: 85,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Shock and awe, Mr. President. We go in fast and hard.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "rice",
                    name: "Condoleezza Rice",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Soviet expert, Provost of Stanford, Later Secretary of State",
                    expertise: 90,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 65,
                    hawkishness: 75,
                    interventionism: 80,
                    fiscalConservatism: 70,
                    adviceAreas: [.intelligence, .diplomacy, .militaryStrike],
                    currentAdvice: "We don't want the smoking gun to be a mushroom cloud.",
                    adviceType: .intelligence,
                    portraitColor: "#FF8C00"
                ),
                Advisor(
                    id: "tenet_bush",
                    name: "George Tenet",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Carried over from Clinton, 'Slam dunk' WMD assessment, Medal of Freedom",
                    expertise: 80,
                    loyalty: 72,
                    influence: 82,
                    publicSupport: 40,
                    hawkishness: 75,
                    interventionism: 80,
                    fiscalConservatism: 60,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "The case on Iraqi WMD is a slam dunk, Mr. President.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "ridge",
                    name: "Tom Ridge",
                    title: "Secretary of Homeland Security",
                    department: "Homeland Security",
                    bio: "Pennsylvania Governor, First DHS Secretary, Color-coded threat system",
                    expertise: 75,
                    loyalty: 85,
                    influence: 78,
                    publicSupport: 60,
                    hawkishness: 65,
                    interventionism: 60,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "We must harden our domestic defenses. Another attack is a matter of when, not if.",
                    adviceType: .intelligence,
                    portraitColor: "#FF8C00"
                ),
                Advisor(
                    id: "negroponte",
                    name: "John Negroponte",
                    title: "Director of National Intelligence",
                    department: "Intelligence Community",
                    bio: "First DNI, Former UN Ambassador, Iraq Ambassador — veteran diplomat",
                    expertise: 85,
                    loyalty: 80,
                    influence: 80,
                    publicSupport: 50,
                    hawkishness: 65,
                    interventionism: 75,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps, .diplomacy],
                    currentAdvice: "Integrating 16 intelligence agencies is a generational challenge. We're making progress.",
                    adviceType: .intelligence,
                    portraitColor: "#4682B4"
                ),
                Advisor(
                    id: "paulson",
                    name: "Hank Paulson",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Goldman Sachs CEO, Financial crisis firefighter, TARP architect",
                    expertise: 92,
                    loyalty: 80,
                    influence: 90,
                    publicSupport: 50,
                    hawkishness: 30,
                    interventionism: 35,
                    fiscalConservatism: 60,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "If we don't stabilize the financial system now, we face a second Great Depression.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                )
            ]
        )
    }

    // MARK: - Obama Administration (2009-2017)

    static func obamaAdministration() -> Administration {
        Administration(
            id: "obama",
            name: "Obama Administration",
            president: "Barack Obama",
            years: "2009-2017",
            startYear: 2009,
            endYear: 2017,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "obama",
                    name: "Barack Obama",
                    title: "President",
                    department: "Executive Office",
                    bio: "44th President, First Black president, Iran nuclear deal, Osama bin Laden raid",
                    expertise: 80,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 55,
                    hawkishness: 45,
                    interventionism: 55,
                    fiscalConservatism: 50,
                    adviceAreas: [.diplomacy, .covertOps, .militaryStrike],
                    currentAdvice: "Let's be clear-eyed about our options. Every decision has consequences.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "clinton_hillary",
                    name: "Hillary Clinton",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Former First Lady, Senator, Libya intervention",
                    expertise: 85,
                    loyalty: 75,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 70,
                    interventionism: 75,
                    fiscalConservatism: 55,
                    adviceAreas: [.diplomacy, .militaryStrike],
                    currentAdvice: "We came, we saw, he died. Sometimes force is necessary.",
                    adviceType: .diplomatic,
                    portraitColor: "#FF1493"
                ),
                Advisor(
                    id: "gates",
                    name: "Robert Gates",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Continued from Bush, Pragmatic military leader",
                    expertise: 95,
                    loyalty: 80,
                    influence: 90,
                    publicSupport: 70,
                    hawkishness: 60,
                    interventionism: 65,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .intelligence],
                    currentAdvice: "Any future Secretary of Defense who advises a president to send a big American land army into Asia or the Middle East should have his head examined.",
                    adviceType: .military,
                    portraitColor: "#556B2F"
                ),
                Advisor(
                    id: "biden_vp",
                    name: "Joe Biden",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Former Senator, Foreign Relations Committee Chairman, Oversaw Iraq withdrawal",
                    expertise: 80,
                    loyalty: 90,
                    influence: 80,
                    publicSupport: 55,
                    hawkishness: 55,
                    interventionism: 65,
                    fiscalConservatism: 50,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "Look, here's the deal - we need to think this through carefully.",
                    adviceType: .diplomatic,
                    portraitColor: "#4682B4"
                ),
                Advisor(
                    id: "brennan",
                    name: "John Brennan",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "30-year CIA veteran, Counterterrorism chief, Drone program architect",
                    expertise: 90,
                    loyalty: 88,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 70,
                    interventionism: 72,
                    fiscalConservatism: 60,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Drone strikes are precise and remove us from nation-building quagmires.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "donilon",
                    name: "Tom Donilon",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Rebalance to Asia architect, bin Laden raid coordinator",
                    expertise: 85,
                    loyalty: 92,
                    influence: 85,
                    publicSupport: 52,
                    hawkishness: 58,
                    interventionism: 62,
                    fiscalConservatism: 55,
                    adviceAreas: [.intelligence, .diplomacy, .militaryStrike],
                    currentAdvice: "The bin Laden intelligence is actionable. We have a window of opportunity.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "geithner",
                    name: "Timothy Geithner",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "NY Fed President, Financial crisis responder, Stress tests architect",
                    expertise: 90,
                    loyalty: 82,
                    influence: 88,
                    publicSupport: 45,
                    hawkishness: 30,
                    interventionism: 38,
                    fiscalConservatism: 65,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Iran sanctions are crippling their economy. Maximum financial pressure is working.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                ),
                Advisor(
                    id: "clapper",
                    name: "James Clapper",
                    title: "Director of National Intelligence",
                    department: "Intelligence Community",
                    bio: "Air Force General, DIA Director, NSA programs oversight",
                    expertise: 87,
                    loyalty: 82,
                    influence: 83,
                    publicSupport: 45,
                    hawkishness: 62,
                    interventionism: 60,
                    fiscalConservatism: 62,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Syria's chemical weapons use crosses a line. Our IC assessment is high-confidence.",
                    adviceType: .intelligence,
                    portraitColor: "#4682B4"
                )
            ]
        )
    }

    // MARK: - Trump First Administration (2017-2021)

    static func trumpFirstAdministration() -> Administration {
        Administration(
            id: "trump_first",
            name: "Trump First Administration",
            president: "Donald Trump",
            years: "2017-2021",
            startYear: 2017,
            endYear: 2021,
            party: "Republican",
            advisors: [
                Advisor(
                    id: "trump_first",
                    name: "Donald J. Trump",
                    title: "President",
                    department: "Executive Office",
                    bio: "45th President, 'Fire and fury', North Korea summit, America First",
                    expertise: 65,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 45,
                    hawkishness: 80,
                    interventionism: 55,
                    fiscalConservatism: 50,
                    adviceAreas: [.militaryStrike, .economicSanctions, .diplomacy],
                    currentAdvice: "Fire and fury like the world has never seen.",
                    adviceType: .military,
                    portraitColor: "#FFD700"
                ),
                Advisor(
                    id: "mattis",
                    name: "James Mattis",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "'Mad Dog', Marine General, Resigned over Syria withdrawal",
                    expertise: 95,
                    loyalty: 60,
                    influence: 85,
                    publicSupport: 75,
                    hawkishness: 75,
                    interventionism: 70,
                    fiscalConservatism: 70,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Be polite, be professional, but have a plan to kill everybody you meet.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "tillerson",
                    name: "Rex Tillerson",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Former Exxon CEO, Fired by Trump",
                    expertise: 75,
                    loyalty: 50,
                    influence: 60,
                    publicSupport: 45,
                    hawkishness: 60,
                    interventionism: 65,
                    fiscalConservatism: 75,
                    adviceAreas: [.diplomacy, .economicSanctions],
                    currentAdvice: "We need to maintain our alliances and commitments, sir.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "pence",
                    name: "Mike Pence",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "Indiana Governor, Evangelical Christian, January 6th certification",
                    expertise: 72,
                    loyalty: 88,
                    influence: 70,
                    publicSupport: 42,
                    hawkishness: 80,
                    interventionism: 78,
                    fiscalConservatism: 82,
                    adviceAreas: [.domesticPolicy, .diplomacy],
                    currentAdvice: "We must stand firm. America's credibility depends on following through.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "bolton",
                    name: "John Bolton",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Ultra-hawk, UN Ambassador, Mustache diplomat, 'The Room Where It Happened'",
                    expertise: 85,
                    loyalty: 55,
                    influence: 80,
                    publicSupport: 40,
                    hawkishness: 99,
                    interventionism: 98,
                    fiscalConservatism: 75,
                    adviceAreas: [.militaryStrike, .covertOps, .nuclearWeapons],
                    currentAdvice: "Regime change in Tehran would solve multiple problems simultaneously.",
                    adviceType: .military,
                    portraitColor: "#8B0000"
                ),
                Advisor(
                    id: "mnuchin",
                    name: "Steven Mnuchin",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Goldman Sachs, Hollywood producer, 'Foreclosure King', Tariff wars manager",
                    expertise: 80,
                    loyalty: 85,
                    influence: 80,
                    publicSupport: 42,
                    hawkishness: 40,
                    interventionism: 42,
                    fiscalConservatism: 60,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Maximum pressure sanctions on Iran and North Korea are squeezing them hard.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                ),
                Advisor(
                    id: "haspel",
                    name: "Gina Haspel",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "First female CIA Director, 'Bloody Gina', Enhanced interrogation overseer",
                    expertise: 88,
                    loyalty: 80,
                    influence: 82,
                    publicSupport: 48,
                    hawkishness: 75,
                    interventionism: 72,
                    fiscalConservatism: 65,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "Our assets confirm the intelligence. The source is reliable.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "pompeo",
                    name: "Mike Pompeo",
                    title: "CIA Director / Secretary of State",
                    department: "CIA / State",
                    bio: "Former Army officer, CIA Director, China hawk, Kansas Congressman",
                    expertise: 85,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 85,
                    interventionism: 80,
                    fiscalConservatism: 70,
                    adviceAreas: [.intelligence, .diplomacy, .militaryStrike],
                    currentAdvice: "We lie, we cheat, we steal. That's the CIA way.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                )
            ]
        )
    }

    // MARK: - Biden Administration (2021-2025)

    static func bidenAdministration() -> Administration {
        Administration(
            id: "biden",
            name: "Biden Administration",
            president: "Joe Biden",
            years: "2021-2025",
            startYear: 2021,
            endYear: 2025,
            party: "Democratic",
            advisors: [
                Advisor(
                    id: "biden_pres",
                    name: "Joe Biden",
                    title: "President",
                    department: "Executive Office",
                    bio: "46th President, Ukraine support, China competition, Oldest president",
                    expertise: 75,
                    loyalty: 100,
                    influence: 100,
                    publicSupport: 42,
                    hawkishness: 50,
                    interventionism: 60,
                    fiscalConservatism: 45,
                    adviceAreas: [.diplomacy, .militaryStrike],
                    currentAdvice: "C'mon man! We need to stand with our allies.",
                    adviceType: .diplomatic,
                    portraitColor: "#4169E1"
                ),
                Advisor(
                    id: "blinken",
                    name: "Antony Blinken",
                    title: "Secretary of State",
                    department: "State",
                    bio: "Deputy Secretary under Obama, Multilateralist",
                    expertise: 85,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 50,
                    interventionism: 70,
                    fiscalConservatism: 50,
                    adviceAreas: [.diplomacy],
                    currentAdvice: "We must rebuild our alliances and lead through diplomacy.",
                    adviceType: .diplomatic,
                    portraitColor: "#1E90FF"
                ),
                Advisor(
                    id: "austin",
                    name: "Lloyd Austin",
                    title: "Secretary of Defense",
                    department: "Defense",
                    bio: "Retired four-star General, First Black Secretary of Defense",
                    expertise: 90,
                    loyalty: 85,
                    influence: 85,
                    publicSupport: 60,
                    hawkishness: 65,
                    interventionism: 70,
                    fiscalConservatism: 60,
                    adviceAreas: [.militaryStrike, .nuclearWeapons],
                    currentAdvice: "Our forces are ready, Mr. President. We maintain deterrence.",
                    adviceType: .military,
                    portraitColor: "#556B2F"
                ),
                Advisor(
                    id: "sullivan",
                    name: "Jake Sullivan",
                    title: "National Security Advisor",
                    department: "NSC",
                    bio: "Former Clinton advisor, Yale Law, Ukraine strategy, China trade architecture",
                    expertise: 80,
                    loyalty: 90,
                    influence: 85,
                    publicSupport: 50,
                    hawkishness: 55,
                    interventionism: 65,
                    fiscalConservatism: 50,
                    adviceAreas: [.intelligence, .diplomacy],
                    currentAdvice: "We're threading the needle on Ukraine — support without escalation to WWIII.",
                    adviceType: .intelligence,
                    portraitColor: "#8B4513"
                ),
                Advisor(
                    id: "harris",
                    name: "Kamala Harris",
                    title: "Vice President",
                    department: "Executive Office",
                    bio: "California Senator, First female VP, First Black and South Asian VP",
                    expertise: 72,
                    loyalty: 85,
                    influence: 72,
                    publicSupport: 40,
                    hawkishness: 45,
                    interventionism: 55,
                    fiscalConservatism: 38,
                    adviceAreas: [.diplomacy, .domesticPolicy],
                    currentAdvice: "We need to address the root causes, not just the symptoms.",
                    adviceType: .diplomatic,
                    portraitColor: "#9400D3"
                ),
                Advisor(
                    id: "burns_cia",
                    name: "William Burns",
                    title: "CIA Director",
                    department: "CIA",
                    bio: "Career diplomat, Russia and Iran expert, Negotiated Iran nuclear deal",
                    expertise: 95,
                    loyalty: 88,
                    influence: 90,
                    publicSupport: 60,
                    hawkishness: 52,
                    interventionism: 58,
                    fiscalConservatism: 62,
                    adviceAreas: [.intelligence, .covertOps, .diplomacy],
                    currentAdvice: "Putin miscalculated on Ukraine. He expected a quick victory. He won't get one.",
                    adviceType: .intelligence,
                    portraitColor: "#2F4F4F"
                ),
                Advisor(
                    id: "yellen",
                    name: "Janet Yellen",
                    title: "Secretary of Treasury",
                    department: "Treasury",
                    bio: "Former Fed Chair, First female Treasury Secretary, Economic sanctions architect",
                    expertise: 97,
                    loyalty: 85,
                    influence: 92,
                    publicSupport: 65,
                    hawkishness: 30,
                    interventionism: 38,
                    fiscalConservatism: 52,
                    adviceAreas: [.economicSanctions, .domesticPolicy],
                    currentAdvice: "Cutting Russia off from SWIFT is the most powerful financial sanction in history.",
                    adviceType: .economic,
                    portraitColor: "#228B22"
                ),
                Advisor(
                    id: "haines",
                    name: "Avril Haines",
                    title: "Director of National Intelligence",
                    department: "Intelligence Community",
                    bio: "First female DNI, Deputy CIA Director, Lawyer, Ukraine intelligence assessments",
                    expertise: 85,
                    loyalty: 88,
                    influence: 83,
                    publicSupport: 55,
                    hawkishness: 55,
                    interventionism: 60,
                    fiscalConservatism: 55,
                    adviceAreas: [.intelligence, .covertOps],
                    currentAdvice: "IC assessment: China is watching Ukraine carefully to gauge our response.",
                    adviceType: .intelligence,
                    portraitColor: "#4682B4"
                )
            ]
        )
    }

    // MARK: - Trump Second Administration (2025-present)

    static func trumpSecondAdministration() -> Administration {
        Administration(
            id: "trump_second",
            name: "Trump Second Administration",
            president: "Donald Trump",
            years: "2025-present",
            startYear: 2025,
            endYear: 2029,
            party: "Republican",
            advisors: trumpCabinet() // Use existing complete cabinet
        )
    }
}
